export class Images {
    public trail = '../../assets/public/images/showcase/';
    public images = {
        antique: [
            this.trail + 'antique/antique_1.jpg',
            this.trail + 'antique/antique_2.jpg',
            this.trail + 'antique/antique_3.jpg',
            this.trail + 'antique/antique_4.jpg',
            this.trail + 'antique/antique_5.jpg',
            this.trail + 'antique/antique_6.jpg'
        ],
        canada: [
            this.trail + 'canada/canada_1.jpg',
            this.trail + 'canada/canada_2.jpg',
            this.trail + 'canada/canada_3.jpg',
            this.trail + 'canada/canada_4.jpg',
            this.trail + 'canada/canada_5.jpg',
            this.trail + 'canada/canada_6.jpg',
            this.trail + 'canada/canada_7.jpg',
            this.trail + 'canada/canada_8.jpg'
        ],
        cartoon: [
            this.trail + 'cartoon/cartoon_1.jpg',
            this.trail + 'cartoon/cartoon_2.jpg',
            this.trail + 'cartoon/cartoon_3.jpg',
            this.trail + 'cartoon/cartoon_4.jpg',
            this.trail + 'cartoon/cartoon_5.jpg',
            this.trail + 'cartoon/cartoon_6.jpg',
            this.trail + 'cartoon/cartoon_7.jpg',
            this.trail + 'cartoon/cartoon_8.jpg',
            this.trail + 'cartoon/cartoon_9.jpg',
            this.trail + 'cartoon/cartoon_10.jpg',
            this.trail + 'cartoon/cartoon_11.jpg',
            this.trail + 'cartoon/cartoon_12.jpg',
            this.trail + 'cartoon/cartoon_13.jpg',
            this.trail + 'cartoon/cartoon_14.jpg',
            this.trail + 'cartoon/cartoon_15.jpg',
            this.trail + 'cartoon/cartoon_16.jpg',
            this.trail + 'cartoon/cartoon_17.jpg',
            this.trail + 'cartoon/cartoon_18.jpg',
            this.trail + 'cartoon/cartoon_19.jpg',
            this.trail + 'cartoon/cartoon_20.jpg',
            this.trail + 'cartoon/cartoon_21.jpg',
            this.trail + 'cartoon/cartoon_22.jpg',
            this.trail + 'cartoon/cartoon_23.jpg'
        ],
        fish: [
            this.trail + 'fish/fish_1.jpg',
            this.trail + 'fish/fish_2.jpg',
            this.trail + 'fish/fish_3.jpg',
            this.trail + 'fish/fish_4.jpg',
            this.trail + 'fish/fish_5.jpg',
            this.trail + 'fish/fish_6.jpg',
            this.trail + 'fish/fish_7.jpg',
            this.trail + 'fish/fish_8.jpg',
            this.trail + 'fish/fish_9.jpg',
            this.trail + 'fish/fish_10.jpg',
            this.trail + 'fish/fish_11.jpg'
        ],
        hockey: [
            this.trail + 'hockey/hockey_1.jpg',
            this.trail + 'hockey/hockey_2.jpg',
            this.trail + 'hockey/hockey_3.jpg',
            this.trail + 'hockey/hockey_4.jpg',
            this.trail + 'hockey/hockey_5.jpg',
            this.trail + 'hockey/hockey_6.jpg',
            this.trail + 'hockey/hockey_7.jpg',
            this.trail + 'hockey/hockey_8.jpg',
            this.trail + 'hockey/hockey_9.jpg'
        ],
        locations: [
            this.trail + 'locations/locations_1.jpg',
            this.trail + 'locations/locations_2.jpg',
            this.trail + 'locations/locations_3.jpg',
            this.trail + 'locations/locations_4.jpg',
            this.trail + 'locations/locations_5.jpg',
            this.trail + 'locations/locations_6.jpg',
            this.trail + 'locations/locations_7.jpg',
            this.trail + 'locations/locations_8.jpg',
            this.trail + 'locations/locations_9.jpg',
            this.trail + 'locations/locations_10.jpg',
            this.trail + 'locations/locations_11.jpg',
            this.trail + 'locations/locations_12.jpg',
            this.trail + 'locations/locations_13.jpg',
            this.trail + 'locations/locations_14.jpg',
            this.trail + 'locations/locations_15.jpg',
            this.trail + 'locations/locations_16.jpg'
        ],
        pride: [
            this.trail + 'pride/pride_1.jpg',
            this.trail + 'pride/pride_2.jpg',
            this.trail + 'pride/pride_3.jpg',
            this.trail + 'pride/pride_4.jpg',
            this.trail + 'pride/pride_5.jpg',
            this.trail + 'pride/pride_6.jpg',
            this.trail + 'pride/pride_7.jpg',
            this.trail + 'pride/pride_8.jpg',
            this.trail + 'pride/pride_9.jpg',
            this.trail + 'pride/pride_10.jpg',
            this.trail + 'pride/pride_11.jpg',
            this.trail + 'pride/pride_12.jpg',
            this.trail + 'pride/pride_13.jpg',
            this.trail + 'pride/pride_14.jpg',
            this.trail + 'pride/pride_15.jpg',
            this.trail + 'pride/pride_16.jpg',
            this.trail + 'pride/pride_17.jpg',
            this.trail + 'pride/pride_18.jpg',
            this.trail + 'pride/pride_19.jpg',
            this.trail + 'pride/pride_20.jpg',
            this.trail + 'pride/pride_21.jpg'
        ],
        wilderness: [
            this.trail + 'wilderness/wilderness_1.jpg',
            this.trail + 'wilderness/wilderness_2.jpg',
            this.trail + 'wilderness/wilderness_3.jpg',
            this.trail + 'wilderness/wilderness_4.jpg',
            this.trail + 'wilderness/wilderness_5.jpg',
            this.trail + 'wilderness/wilderness_6.jpg',
            this.trail + 'wilderness/wilderness_7.jpg',
            this.trail + 'wilderness/wilderness_8.jpg',
            this.trail + 'wilderness/wilderness_9.jpg',
            this.trail + 'wilderness/wilderness_10.jpg',
            this.trail + 'wilderness/wilderness_11.jpg',
            this.trail + 'wilderness/wilderness_12.jpg',
            this.trail + 'wilderness/wilderness_13.jpg',
            this.trail + 'wilderness/wilderness_14.jpg',
            this.trail + 'wilderness/wilderness_15.jpg',
            this.trail + 'wilderness/wilderness_16.jpg',
            this.trail + 'wilderness/wilderness_17.jpg',
        ]
    };
}
